### PR TITLE
Clean up some protocol details, add python implementation

### PR DESCRIPTION
**Pull request by jaxxzer**

### CODE REVIEW

**Comment by patrickelectric** [comment]
I did a PR that squash all my commits with the necessary ones, besides that I was not able to finish what I'm planning to do. I'll do a future PR to organize the python library better, right now some things are directly hardcoded and with redundant info between files, besides that, the unrelated usage of the serial device to just use the protocol does not make sense to me.
Last points:
- Profile does not pass in Ping1D but works in PingMessage.
```
	---Testing profile---
	
	
	
	--------------------------------------------------
	ID: 1300 - profile
	Header: start_1: 66 start_2: 82 payload_length: 30 message_id: 1300 src_device_id: 5 dst_device_id: 6
	Payload:
	  - distance: 1819043176
	  - confidence: 111
	  - pulse_usec: 26624
	  - ping_number: 1869376613
	  - scan_start: 1701314560
	  - scan_length: 7302252
	  - gain_index: 1818585088
	  - num_points: 28524
	  - data: ['0x1', '0x2', '0x63', '0x64']
	Checksum: 2738 check: 2544 pass: False
	```
- PingMessage is still not compatible with python3
- Ping1D not compatible with python3

I'll be ok if you want to merge the [`python2` PR](https://github.com/bluerobotics/ping-protocol-cpp/pull/59) with the squashed commits. This will allow us to continue our work for the upcoming days.

**Comment by jaxxzer** [comment]
This is the expected behavior for the test in PingMessage. I hard coded a bad checksum.

**Comment by jaxxzer** [comment]
Can you give me some info on how you want to change the class? Is the interface going to change? The Ping1D.py is analagous to the ping.cpp in ping-viewer.

**Comment by patrickelectric** [comment]
I was able to remove all generated get messages with:
```
def __getattr__(self, name, value=None):
        print('name', name, name[:4] == 'get_', value)
        id = None
        output = None
        # Get messages
        if name[:4] == 'get_':
            for d in PingMessage.payloadDict:
                if PingMessage.payloadDict[d]['name'] == name[4:]:
                    id = d
                    break
            else:
                print('Message with name %s not found !' % name[4:])
                return lambda:None

            if self.request(id) is None:
                print('request is none')
                return lambda:None

        # If message exist, return dict
        if id:
            output = {key:self.data[key] for key in PingMessage.payloadDict[id]['field_names']}
```

Inside this function, I was working to remove all set functions with a abstract set function.

Adding this test in the previous function:
```
        # Set messages
        if name[:4] == 'set_':
            return lambda *args:self.set(name, args)
```

You could create a self.set function that:
```
def set(self, *args):
        # Get message name and args
        name = args[0]
        args = args[1:]
        id = 0
        msg_payload = {}
        for d in PingMessage.payloadDict:
            if PingMessage.payloadDict[d]['name'] == name[4:]:
                id = d
                msg_payload = {key:self.data[key] for key in PingMessage.payloadDict[id]['field_names']}
                break
        else:
            print('Message with name %s not found !' % name[4:])
            return None
		# from here, get the payload, create the necessary function, send it to the sensor and check if it's correct.
```

The last step was hard, because the PingMessage was not create with a dict to hold all the data. With that done, it would possible to use it with `__getattr__` to get all the necessary data as a variable inside the class. This would make the Ping1D simpler and less redundant with PingMessage.
I was not able to finish the last step health/time issues, with that a created the python2 patch if you want it ready to merge.

**Comment by jaxxzer** [comment]
Closing in favor of #59

**Pull request closed without merging**
